title: "Bonding Through Coding"
email: "your-email@example.com"
description: "A guide to HTML and CSS for kids."
baseurl: "/resources"
url: "https://bondingthroughcoding.github.io"
theme: minima
markdown: kramdown
