title: "Bonding Through Coding"
email: "your-email@example.com"
description: "A guide to HTML and CSS for kids."
baseurl: ""
url: "https://bondingthroughcoding.github.io"
theme: jekyll-theme-minimal
markdown: kramdown
