title: Bonding T2hrough Coding
description: Tech fun for kids! Learn HTML & CSS with simple, interactive lessons. 
theme: minima # Or a  ny GitHub Pages-supported theme
markdown: kramdown


collections:
  nav:
    output: false
